//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/AbstractCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsAbstractCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsAbstractCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsAbstractCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsAbstractCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsAbstractCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsAbstractCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsAbstractCommand))
#define ComJhonjuPs3netsrvServerCommandsAbstractCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsICommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsICommand 1
#include "com/jhonju/ps3netsrv/server/commands/ICommand.h"

@class ComJhonjuPs3netsrvServerContext;
@class IOSByteArray;
@protocol ComJhonjuPs3netsrvServerCommandsIResult;

@interface ComJhonjuPs3netsrvServerCommandsAbstractCommand : NSObject < ComJhonjuPs3netsrvServerCommandsICommand > {
 @public
  ComJhonjuPs3netsrvServerContext *ctx_;
  IOSByteArray *ERROR_CODE_BYTEARRAY_;
  IOSByteArray *SUCCESS_CODE_BYTEARRAY_;
}

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx;

#pragma mark Protected

- (void)sendWithByteArray:(IOSByteArray *)result;

- (void)sendWithComJhonjuPs3netsrvServerCommandsIResult:(id<ComJhonjuPs3netsrvServerCommandsIResult>)result;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsAbstractCommand)

J2OBJC_FIELD_SETTER(ComJhonjuPs3netsrvServerCommandsAbstractCommand, ctx_, ComJhonjuPs3netsrvServerContext *)
J2OBJC_FIELD_SETTER(ComJhonjuPs3netsrvServerCommandsAbstractCommand, ERROR_CODE_BYTEARRAY_, IOSByteArray *)
J2OBJC_FIELD_SETTER(ComJhonjuPs3netsrvServerCommandsAbstractCommand, SUCCESS_CODE_BYTEARRAY_, IOSByteArray *)

inline jint ComJhonjuPs3netsrvServerCommandsAbstractCommand_get_ERROR_CODE(void);
#define ComJhonjuPs3netsrvServerCommandsAbstractCommand_ERROR_CODE -1
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsAbstractCommand, ERROR_CODE, jint)

inline jint ComJhonjuPs3netsrvServerCommandsAbstractCommand_get_EMPTY_SIZE(void);
#define ComJhonjuPs3netsrvServerCommandsAbstractCommand_EMPTY_SIZE 0
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsAbstractCommand, EMPTY_SIZE, jint)

inline jint ComJhonjuPs3netsrvServerCommandsAbstractCommand_get_BUFFER_SIZE(void);
#define ComJhonjuPs3netsrvServerCommandsAbstractCommand_BUFFER_SIZE 4194304
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsAbstractCommand, BUFFER_SIZE, jint)

inline jint ComJhonjuPs3netsrvServerCommandsAbstractCommand_get_BYTES_TO_SKIP(void);
#define ComJhonjuPs3netsrvServerCommandsAbstractCommand_BYTES_TO_SKIP 24
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsAbstractCommand, BYTES_TO_SKIP, jint)

inline jshort ComJhonjuPs3netsrvServerCommandsAbstractCommand_get_MILLISECONDS_IN_SECOND(void);
#define ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND 1000
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsAbstractCommand, MILLISECONDS_IN_SECOND, jshort)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsAbstractCommand_initWithComJhonjuPs3netsrvServerContext_(ComJhonjuPs3netsrvServerCommandsAbstractCommand *self, ComJhonjuPs3netsrvServerContext *ctx);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsAbstractCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsAbstractCommand")
