//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/CreateFileCommand.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/Context.h"
#include "com/jhonju/ps3netsrv/server/commands/CreateFileCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"
#include "com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException.h"
#include "java/io/File.h"
#include "java/io/IOException.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/commands/CreateFileCommand must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComJhonjuPs3netsrvServerCommandsCreateFileCommand

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength {
  ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
  return self;
}

- (void)executeTask {
  if ([((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) isReadOnly]) {
    [self sendWithByteArray:ERROR_CODE_BYTEARRAY_];
    @throw create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(@"Failed to create file: server is executing as read only");
  }
  @try {
    JavaIoFile *file = JreRetainedLocalValue([self getFile]);
    [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setWriteOnlyFileWithJavaIoFile:nil];
    if ([((JavaIoFile *) nil_chk(file)) isDirectory]) {
      @throw create_JavaIoIOException_initWithNSString_(JreStrcat("$$", @"ERROR: file is a directory: ", [file getCanonicalPath]));
    }
    if (![file createNewFile]) {
      @throw create_JavaIoIOException_initWithNSString_(JreStrcat("$$", @"ERROR: create error on ", [file getCanonicalPath]));
    }
    [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setWriteOnlyFileWithJavaIoFile:file];
    [self sendWithByteArray:SUCCESS_CODE_BYTEARRAY_];
  }
  @catch (JavaIoIOException *ex) {
    [self sendWithByteArray:ERROR_CODE_BYTEARRAY_];
    @throw create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_([ex getMessage]);
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComJhonjuPs3netsrvServerContext:withShort:);
  methods[1].selector = @selector(executeTask);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComJhonjuPs3netsrvServerContext;S", "LComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;LJavaIoIOException;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsCreateFileCommand = { "CreateFileCommand", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsCreateFileCommand;
}

@end

void ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsCreateFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  ComJhonjuPs3netsrvServerCommandsFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
}

ComJhonjuPs3netsrvServerCommandsCreateFileCommand *new_ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsCreateFileCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

ComJhonjuPs3netsrvServerCommandsCreateFileCommand *create_ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsCreateFileCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsCreateFileCommand)
