//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/CreateFileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsCreateFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsCreateFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsCreateFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsCreateFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsCreateFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsCreateFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsCreateFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsCreateFileCommand))
#define ComJhonjuPs3netsrvServerCommandsCreateFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsCreateFileCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsCreateFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsCreateFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsCreateFileCommand *new_ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsCreateFileCommand *create_ComJhonjuPs3netsrvServerCommandsCreateFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsCreateFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsCreateFileCommand")
