//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/DeleteFileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsDeleteFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand))
#define ComJhonjuPs3netsrvServerCommandsDeleteFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsDeleteFileCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsDeleteFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsDeleteFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsDeleteFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsDeleteFileCommand *new_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsDeleteFileCommand *create_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsDeleteFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsDeleteFileCommand")
