//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/FileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand))
#define ComJhonjuPs3netsrvServerCommandsFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"

@class ComJhonjuPs3netsrvServerContext;
@class JavaIoFile;

@interface ComJhonjuPs3netsrvServerCommandsFileCommand : ComJhonjuPs3netsrvServerCommandsAbstractCommand {
 @public
  jshort filePathLength_;
}

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

#pragma mark Protected

- (JavaIoFile *)getFile;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsFileCommand")
