//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/GetDirSizeCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand))
#define ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand *new_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand *create_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsGetDirSizeCommand")
