//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/ICommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsICommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsICommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsICommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsICommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsICommand

#if !defined (ComJhonjuPs3netsrvServerCommandsICommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsICommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsICommand))
#define ComJhonjuPs3netsrvServerCommandsICommand_

@protocol ComJhonjuPs3netsrvServerCommandsICommand < JavaObject >

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsICommand)

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsICommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsICommand")
