//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/IResult.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsIResult")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsIResult
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsIResult 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsIResult 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsIResult

#if !defined (ComJhonjuPs3netsrvServerCommandsIResult_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsIResult || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsIResult))
#define ComJhonjuPs3netsrvServerCommandsIResult_

@class IOSByteArray;

@protocol ComJhonjuPs3netsrvServerCommandsIResult < JavaObject >

- (IOSByteArray *)toByteArray;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsIResult)

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsIResult)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsIResult")
