//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/MakeDirCommand.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/Context.h"
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/MakeDirCommand.h"
#include "com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException.h"
#include "java/io/File.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/commands/MakeDirCommand must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComJhonjuPs3netsrvServerCommandsMakeDirCommand

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength {
  ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
  return self;
}

- (void)executeTask {
  if ([((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) isReadOnly]) {
    [self sendWithByteArray:ERROR_CODE_BYTEARRAY_];
    @throw create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(@"Failed to make dir: server is executing as read only");
  }
  [self sendWithByteArray:[((JavaIoFile *) nil_chk([self getFile])) mkdir] ? SUCCESS_CODE_BYTEARRAY_ : ERROR_CODE_BYTEARRAY_];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComJhonjuPs3netsrvServerContext:withShort:);
  methods[1].selector = @selector(executeTask);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComJhonjuPs3netsrvServerContext;S", "LComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;LJavaIoIOException;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsMakeDirCommand = { "MakeDirCommand", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsMakeDirCommand;
}

@end

void ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsMakeDirCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  ComJhonjuPs3netsrvServerCommandsFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
}

ComJhonjuPs3netsrvServerCommandsMakeDirCommand *new_ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsMakeDirCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

ComJhonjuPs3netsrvServerCommandsMakeDirCommand *create_ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsMakeDirCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsMakeDirCommand)
