//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/MakeDirCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsMakeDirCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsMakeDirCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsMakeDirCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsMakeDirCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsMakeDirCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsMakeDirCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsMakeDirCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsMakeDirCommand))
#define ComJhonjuPs3netsrvServerCommandsMakeDirCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsMakeDirCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsMakeDirCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsMakeDirCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsMakeDirCommand *new_ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsMakeDirCommand *create_ComJhonjuPs3netsrvServerCommandsMakeDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsMakeDirCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsMakeDirCommand")
