//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/OpenFileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsOpenFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsOpenFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsOpenFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsOpenFileCommand))
#define ComJhonjuPs3netsrvServerCommandsOpenFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsOpenFileCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsOpenFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsOpenFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsOpenFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsOpenFileCommand *new_ComJhonjuPs3netsrvServerCommandsOpenFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsOpenFileCommand *create_ComJhonjuPs3netsrvServerCommandsOpenFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsOpenFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenFileCommand")
