//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/OpenDirCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenDirCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsOpenDirCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenDirCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenDirCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsOpenDirCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsOpenDirCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenDirCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsOpenDirCommand))
#define ComJhonjuPs3netsrvServerCommandsOpenDirCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsOpenDirCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsOpenDirCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsOpenDirCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsOpenDirCommand *new_ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsOpenDirCommand *create_ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsOpenDirCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsOpenDirCommand")
