//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/OpenDirCommand.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/Context.h"
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/OpenDirCommand.h"
#include "java/io/File.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/commands/OpenDirCommand must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComJhonjuPs3netsrvServerCommandsOpenDirCommand

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength {
  ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
  return self;
}

- (void)executeTask {
  JavaIoFile *file = JreRetainedLocalValue([self getFile]);
  if ([((JavaIoFile *) nil_chk(file)) exists]) {
    [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setFileWithJavaIoFile:file];
    [self sendWithByteArray:[file isDirectory] ? SUCCESS_CODE_BYTEARRAY_ : ERROR_CODE_BYTEARRAY_];
  }
  else {
    [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setFileWithJavaIoFile:nil];
    [self sendWithByteArray:ERROR_CODE_BYTEARRAY_];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComJhonjuPs3netsrvServerContext:withShort:);
  methods[1].selector = @selector(executeTask);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComJhonjuPs3netsrvServerContext;S", "LComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;LJavaIoIOException;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsOpenDirCommand = { "OpenDirCommand", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsOpenDirCommand;
}

@end

void ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsOpenDirCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  ComJhonjuPs3netsrvServerCommandsFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
}

ComJhonjuPs3netsrvServerCommandsOpenDirCommand *new_ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsOpenDirCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

ComJhonjuPs3netsrvServerCommandsOpenDirCommand *create_ComJhonjuPs3netsrvServerCommandsOpenDirCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsOpenDirCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsOpenDirCommand)
