//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/ReadFileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsReadFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsReadFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsReadFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsReadFileCommand))
#define ComJhonjuPs3netsrvServerCommandsReadFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsReadFileCommand : ComJhonjuPs3netsrvServerCommandsAbstractCommand {
 @public
  jint numBytes_;
  jlong offset_;
}

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                                withInt:(jint)numBytes
                                               withLong:(jlong)offset;

- (void)executeTask;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsReadFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsReadFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerCommandsReadFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsReadFileCommand *new_ComJhonjuPs3netsrvServerCommandsReadFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsReadFileCommand *create_ComJhonjuPs3netsrvServerCommandsReadFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsReadFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCommand")
