//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/ReadDirEntryCommandV2.java
//

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/Context.h"
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/IResult.h"
#include "com/jhonju/ps3netsrv/server/commands/ReadDirEntryCommandV2.h"
#include "com/jhonju/ps3netsrv/server/utils/Utils.h"
#include "java/io/ByteArrayOutputStream.h"
#include "java/io/File.h"
#include "java/lang/Throwable.h"
#include "java/nio/charset/Charset.h"
#include "java/nio/charset/StandardCharsets.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/commands/ReadDirEntryCommandV2 must not be compiled with ARC (-fobjc-arc)"
#endif

inline jint ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_get_RESULT_LENGTH(void);
#define ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_RESULT_LENGTH 290
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2, RESULT_LENGTH, jint)

inline jshort ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_get_MAX_FILE_NAME_LENGTH(void);
#define ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_MAX_FILE_NAME_LENGTH 255
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2, MAX_FILE_NAME_LENGTH, jshort)

inline jshort ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_get_EMPTY_FILE_NAME_LENGTH(void);
#define ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_EMPTY_FILE_NAME_LENGTH 0
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2, EMPTY_FILE_NAME_LENGTH, jshort)

@interface ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 : NSObject < ComJhonjuPs3netsrvServerCommandsIResult > {
 @public
  jlong aFileSize_;
  jlong bModifiedTime_;
  jlong cCreationTime_;
  jlong dAccessedTime_;
  jshort eFileNameLength_;
  jboolean fIsDirectory_;
  NSString *gFileName_;
}

- (instancetype)init;

- (instancetype)initWithLong:(jlong)aFileSize
                    withLong:(jlong)bModifiedTime
                    withLong:(jlong)cCreationTime
                    withLong:(jlong)dAccessedTime
                   withShort:(jshort)eFileNameLength
                 withBoolean:(jboolean)fIsDirectory
                withNSString:(NSString *)gFileName;

- (IOSByteArray *)toByteArray;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2)

J2OBJC_FIELD_SETTER(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2, gFileName_, NSString *)

__attribute__((unused)) static void ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *self);

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *new_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init(void);

__attribute__((unused)) static void ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *self, jlong aFileSize, jlong bModifiedTime, jlong cCreationTime, jlong dAccessedTime, jshort eFileNameLength, jboolean fIsDirectory, NSString *gFileName);

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *new_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(jlong aFileSize, jlong bModifiedTime, jlong cCreationTime, jlong dAccessedTime, jshort eFileNameLength, jboolean fIsDirectory, NSString *gFileName) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(jlong aFileSize, jlong bModifiedTime, jlong cCreationTime, jlong dAccessedTime, jshort eFileNameLength, jboolean fIsDirectory, NSString *gFileName);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2)

@implementation ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx {
  ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_initWithComJhonjuPs3netsrvServerContext_(self, ctx);
  return self;
}

- (void)executeTask {
  JavaIoFile *file = JreRetainedLocalValue([((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) getFile]);
  if (file == nil || ![file isDirectory]) {
    [self sendWithComJhonjuPs3netsrvServerCommandsIResult:create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init()];
    return;
  }
  JavaIoFile *fileAux = nil;
  IOSObjectArray *fileList = [file list];
  if (fileList != nil) {
    {
      IOSObjectArray *a__ = fileList;
      NSString * const *b__ = a__->buffer_;
      NSString * const *e__ = b__ + a__->size_;
      while (b__ < e__) {
        NSString *fileName = *b__++;
        fileAux = create_JavaIoFile_initWithNSString_(JreStrcat("$C$", [file getCanonicalPath], '/', fileName));
        if ([((NSString *) nil_chk([fileAux getName])) java_length] <= ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_MAX_FILE_NAME_LENGTH) {
          break;
        }
      }
    }
  }
  if (fileAux == nil) {
    [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setFileWithJavaIoFile:nil];
    [self sendWithComJhonjuPs3netsrvServerCommandsIResult:create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init()];
    return;
  }
  IOSLongArray *fileTimes = ComJhonjuPs3netsrvServerUtilsUtils_getFileStatsWithJavaIoFile_(fileAux);
  [self sendWithComJhonjuPs3netsrvServerCommandsIResult:create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_([fileAux isDirectory] ? ComJhonjuPs3netsrvServerCommandsAbstractCommand_EMPTY_SIZE : [file length], JreLongDiv([fileAux lastModified], ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), JreLongDiv(IOSLongArray_Get(nil_chk(fileTimes), 0), ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), JreLongDiv(IOSLongArray_Get(fileTimes, 1), ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), (jshort) [((NSString *) nil_chk([fileAux getName])) java_length], [fileAux isDirectory], [fileAux getName])];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComJhonjuPs3netsrvServerContext:);
  methods[1].selector = @selector(executeTask);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "RESULT_LENGTH", "I", .constantValue.asInt = ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_RESULT_LENGTH, 0x1a, -1, -1, -1, -1 },
    { "MAX_FILE_NAME_LENGTH", "S", .constantValue.asShort = ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_MAX_FILE_NAME_LENGTH, 0x1a, -1, -1, -1, -1 },
    { "EMPTY_FILE_NAME_LENGTH", "S", .constantValue.asShort = ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_EMPTY_FILE_NAME_LENGTH, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComJhonjuPs3netsrvServerContext;", "LJavaIoIOException;LComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;", "LComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2 = { "ReadDirEntryCommandV2", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, fields, 7, 0x1, 2, 3, -1, 2, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2;
}

@end

void ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_initWithComJhonjuPs3netsrvServerContext_(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2 *self, ComJhonjuPs3netsrvServerContext *ctx) {
  ComJhonjuPs3netsrvServerCommandsAbstractCommand_initWithComJhonjuPs3netsrvServerContext_(self, ctx);
}

ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2 *new_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_initWithComJhonjuPs3netsrvServerContext_(ComJhonjuPs3netsrvServerContext *ctx) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2, initWithComJhonjuPs3netsrvServerContext_, ctx)
}

ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2 *create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_initWithComJhonjuPs3netsrvServerContext_(ComJhonjuPs3netsrvServerContext *ctx) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2, initWithComJhonjuPs3netsrvServerContext_, ctx)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2)

@implementation ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (instancetype)initWithLong:(jlong)aFileSize
                    withLong:(jlong)bModifiedTime
                    withLong:(jlong)cCreationTime
                    withLong:(jlong)dAccessedTime
                   withShort:(jshort)eFileNameLength
                 withBoolean:(jboolean)fIsDirectory
                withNSString:(NSString *)gFileName {
  ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(self, aFileSize, bModifiedTime, cCreationTime, dAccessedTime, eFileNameLength, fIsDirectory, gFileName);
  return self;
}

- (IOSByteArray *)toByteArray {
  JavaIoByteArrayOutputStream *out = create_JavaIoByteArrayOutputStream_initWithInt_(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_RESULT_LENGTH);
  JavaLangThrowable *__primaryException1 = nil;
  @try {
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->aFileSize_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->bModifiedTime_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->cCreationTime_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->dAccessedTime_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_shortToBytesBEWithShort_(self->eFileNameLength_)];
    [out writeWithInt:fIsDirectory_ ? 1 : 0];
    if (gFileName_ != nil) {
      [out writeWithByteArray:[gFileName_ java_getBytesWithCharset:JreLoadStatic(JavaNioCharsetStandardCharsets, UTF_8)]];
    }
    return [out toByteArray];
  }
  @catch (JavaLangThrowable *e) {
    __primaryException1 = e;
    @throw e;
  }
  @finally {
    if (out != nil) {
      if (__primaryException1 != nil) {
        @try {
          [out close];
        }
        @catch (JavaLangThrowable *e) {
          [__primaryException1 addSuppressedWithJavaLangThrowable:e];
        }
      }
      else {
        [out close];
      }
    }
  }
}

- (void)dealloc {
  RELEASE_(gFileName_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initWithLong:withLong:withLong:withLong:withShort:withBoolean:withNSString:);
  methods[2].selector = @selector(toByteArray);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "aFileSize_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "bModifiedTime_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "cCreationTime_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "dAccessedTime_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "eFileNameLength_", "S", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "fIsDirectory_", "Z", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "gFileName_", "LNSString;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "JJJJSZLNSString;", "LJavaIoIOException;", "LComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 = { "ReadDirEntryResultV2", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, fields, 7, 0xa, 3, 7, 2, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2;
}

@end

void ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *self) {
  NSObject_init(self);
  self->aFileSize_ = ComJhonjuPs3netsrvServerCommandsAbstractCommand_EMPTY_SIZE;
  self->bModifiedTime_ = 0LL;
  self->cCreationTime_ = 0LL;
  self->dAccessedTime_ = 0LL;
  self->eFileNameLength_ = ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_EMPTY_FILE_NAME_LENGTH;
  self->fIsDirectory_ = false;
  JreStrongAssign(&self->gFileName_, nil);
}

ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *new_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init() {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2, init)
}

ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_init() {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2, init)
}

void ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *self, jlong aFileSize, jlong bModifiedTime, jlong cCreationTime, jlong dAccessedTime, jshort eFileNameLength, jboolean fIsDirectory, NSString *gFileName) {
  NSObject_init(self);
  self->aFileSize_ = aFileSize;
  self->bModifiedTime_ = bModifiedTime;
  self->cCreationTime_ = cCreationTime;
  self->dAccessedTime_ = dAccessedTime;
  self->eFileNameLength_ = eFileNameLength;
  self->fIsDirectory_ = fIsDirectory;
  JreStrongAssign(&self->gFileName_, gFileName);
}

ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *new_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(jlong aFileSize, jlong bModifiedTime, jlong cCreationTime, jlong dAccessedTime, jshort eFileNameLength, jboolean fIsDirectory, NSString *gFileName) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2, initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_, aFileSize, bModifiedTime, cCreationTime, dAccessedTime, eFileNameLength, fIsDirectory, gFileName)
}

ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2 *create_ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2_initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_(jlong aFileSize, jlong bModifiedTime, jlong cCreationTime, jlong dAccessedTime, jshort eFileNameLength, jboolean fIsDirectory, NSString *gFileName) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2, initWithLong_withLong_withLong_withLong_withShort_withBoolean_withNSString_, aFileSize, bModifiedTime, cCreationTime, dAccessedTime, eFileNameLength, fIsDirectory, gFileName)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsReadDirEntryCommandV2_ReadDirEntryResultV2)
