//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/ReadFileCriticalCommand.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/Context.h"
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/ReadFileCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/ReadFileCriticalCommand.h"
#include "com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException.h"
#include "java/io/IOException.h"
#include "java/io/RandomAccessFile.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/commands/ReadFileCriticalCommand must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                                withInt:(jint)numBytes
                                               withLong:(jlong)offset {
  ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(self, ctx, numBytes, offset);
  return self;
}

- (void)executeTask {
  IOSByteArray *result = [IOSByteArray arrayWithLength:numBytes_];
  JavaIoRandomAccessFile *file = JreRetainedLocalValue([((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) getReadOnlyFile]);
  @try {
    [((JavaIoRandomAccessFile *) nil_chk(file)) seekWithLong:offset_];
    if ([file readWithByteArray:result] < ComJhonjuPs3netsrvServerCommandsAbstractCommand_EMPTY_SIZE) {
      @throw create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(@"Error reading file. EOF");
    }
  }
  @catch (JavaIoIOException *e) {
    @throw create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(@"Error reading file.");
  }
  [self sendWithByteArray:result];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComJhonjuPs3netsrvServerContext:withInt:withLong:);
  methods[1].selector = @selector(executeTask);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LComJhonjuPs3netsrvServerContext;IJ", "LJavaIoIOException;LComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand = { "ReadFileCriticalCommand", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand;
}

@end

void ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset) {
  ComJhonjuPs3netsrvServerCommandsReadFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(self, ctx, numBytes, offset);
}

ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand *new_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand, initWithComJhonjuPs3netsrvServerContext_withInt_withLong_, ctx, numBytes, offset)
}

ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand *create_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand, initWithComJhonjuPs3netsrvServerContext_withInt_withLong_, ctx, numBytes, offset)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand)
