//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/ReadFileCriticalCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand))
#define ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsReadFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsReadFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/ReadFileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand : ComJhonjuPs3netsrvServerCommandsReadFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                                withInt:(jint)numBytes
                                               withLong:(jlong)offset;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand *new_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand *create_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand_initWithComJhonjuPs3netsrvServerContext_withInt_withLong_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes, jlong offset);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadFileCriticalCommand")
