//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/ReadCD2048Command.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadCD2048Command")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsReadCD2048Command
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadCD2048Command 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadCD2048Command 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsReadCD2048Command

#if !defined (ComJhonjuPs3netsrvServerCommandsReadCD2048Command_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadCD2048Command || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsReadCD2048Command))
#define ComJhonjuPs3netsrvServerCommandsReadCD2048Command_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsReadCD2048Command : ComJhonjuPs3netsrvServerCommandsAbstractCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                                withInt:(jint)startSector
                                                withInt:(jint)sectorCount;

- (void)executeTask;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsReadCD2048Command)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsReadCD2048Command_initWithComJhonjuPs3netsrvServerContext_withInt_withInt_(ComJhonjuPs3netsrvServerCommandsReadCD2048Command *self, ComJhonjuPs3netsrvServerContext *ctx, jint startSector, jint sectorCount);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsReadCD2048Command *new_ComJhonjuPs3netsrvServerCommandsReadCD2048Command_initWithComJhonjuPs3netsrvServerContext_withInt_withInt_(ComJhonjuPs3netsrvServerContext *ctx, jint startSector, jint sectorCount) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsReadCD2048Command *create_ComJhonjuPs3netsrvServerCommandsReadCD2048Command_initWithComJhonjuPs3netsrvServerContext_withInt_withInt_(ComJhonjuPs3netsrvServerContext *ctx, jint startSector, jint sectorCount);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsReadCD2048Command)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsReadCD2048Command")
