//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/StatFileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsStatFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsStatFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsStatFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsStatFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsStatFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsStatFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsStatFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsStatFileCommand))
#define ComJhonjuPs3netsrvServerCommandsStatFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsFileCommand 1
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsStatFileCommand : ComJhonjuPs3netsrvServerCommandsFileCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength;

- (void)executeTask;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsStatFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsStatFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsStatFileCommand *new_ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsStatFileCommand *create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsStatFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsStatFileCommand")
