//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/StatFileCommand.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/Context.h"
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/FileCommand.h"
#include "com/jhonju/ps3netsrv/server/commands/IResult.h"
#include "com/jhonju/ps3netsrv/server/commands/StatFileCommand.h"
#include "com/jhonju/ps3netsrv/server/utils/Utils.h"
#include "java/io/ByteArrayOutputStream.h"
#include "java/io/File.h"
#include "java/lang/Throwable.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/commands/StatFileCommand must not be compiled with ARC (-fobjc-arc)"
#endif

inline jint ComJhonjuPs3netsrvServerCommandsStatFileCommand_get_RESULT_LENGTH(void);
#define ComJhonjuPs3netsrvServerCommandsStatFileCommand_RESULT_LENGTH 33
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerCommandsStatFileCommand, RESULT_LENGTH, jint)

@interface ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult : NSObject < ComJhonjuPs3netsrvServerCommandsIResult > {
 @public
  jlong aFileSize_;
  jlong bModifiedTime_;
  jlong cCreationTime_;
  jlong dLastAccessTime_;
  jboolean eIsDirectory_;
}

- (instancetype)initWithLong:(jlong)fileSize
                    withLong:(jlong)modifiedTime
                    withLong:(jlong)creationTime
                    withLong:(jlong)lastAccessTime
                 withBoolean:(jboolean)isDirectory;

- (instancetype)init;

- (IOSByteArray *)toByteArray;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult)

__attribute__((unused)) static void ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *self, jlong fileSize, jlong modifiedTime, jlong creationTime, jlong lastAccessTime, jboolean isDirectory);

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *new_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(jlong fileSize, jlong modifiedTime, jlong creationTime, jlong lastAccessTime, jboolean isDirectory) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(jlong fileSize, jlong modifiedTime, jlong creationTime, jlong lastAccessTime, jboolean isDirectory);

__attribute__((unused)) static void ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *self);

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *new_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init(void) NS_RETURNS_RETAINED;

__attribute__((unused)) static ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult)

@implementation ComJhonjuPs3netsrvServerCommandsStatFileCommand

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                              withShort:(jshort)filePathLength {
  ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
  return self;
}

- (void)executeTask {
  [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setFileWithJavaIoFile:nil];
  JavaIoFile *file = JreRetainedLocalValue([self getFile]);
  if ([((JavaIoFile *) nil_chk(file)) exists]) {
    [((ComJhonjuPs3netsrvServerContext *) nil_chk(ctx_)) setFileWithJavaIoFile:file];
    ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *statResult;
    if ([file isDirectory]) {
      statResult = create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(ComJhonjuPs3netsrvServerCommandsAbstractCommand_EMPTY_SIZE, JreLongDiv([file lastModified], ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), JreLongDiv([file lastModified], ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), 0, true);
    }
    else {
      IOSLongArray *fileStats = ComJhonjuPs3netsrvServerUtilsUtils_getFileStatsWithJavaIoFile_(file);
      statResult = create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_([file length], JreLongDiv([file lastModified], ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), JreLongDiv(IOSLongArray_Get(nil_chk(fileStats), 0), ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), JreLongDiv(IOSLongArray_Get(fileStats, 1), ComJhonjuPs3netsrvServerCommandsAbstractCommand_MILLISECONDS_IN_SECOND), false);
    }
    [self sendWithComJhonjuPs3netsrvServerCommandsIResult:statResult];
  }
  else {
    [self sendWithComJhonjuPs3netsrvServerCommandsIResult:create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init()];
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "V", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithComJhonjuPs3netsrvServerContext:withShort:);
  methods[1].selector = @selector(executeTask);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "RESULT_LENGTH", "I", .constantValue.asInt = ComJhonjuPs3netsrvServerCommandsStatFileCommand_RESULT_LENGTH, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LComJhonjuPs3netsrvServerContext;S", "LJavaIoIOException;LComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;", "LComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsStatFileCommand = { "StatFileCommand", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, fields, 7, 0x1, 2, 1, -1, 2, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsStatFileCommand;
}

@end

void ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerCommandsStatFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  ComJhonjuPs3netsrvServerCommandsFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(self, ctx, filePathLength);
}

ComJhonjuPs3netsrvServerCommandsStatFileCommand *new_ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsStatFileCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

ComJhonjuPs3netsrvServerCommandsStatFileCommand *create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_initWithComJhonjuPs3netsrvServerContext_withShort_(ComJhonjuPs3netsrvServerContext *ctx, jshort filePathLength) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsStatFileCommand, initWithComJhonjuPs3netsrvServerContext_withShort_, ctx, filePathLength)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsStatFileCommand)

@implementation ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult

- (instancetype)initWithLong:(jlong)fileSize
                    withLong:(jlong)modifiedTime
                    withLong:(jlong)creationTime
                    withLong:(jlong)lastAccessTime
                 withBoolean:(jboolean)isDirectory {
  ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(self, fileSize, modifiedTime, creationTime, lastAccessTime, isDirectory);
  return self;
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

- (IOSByteArray *)toByteArray {
  JavaIoByteArrayOutputStream *out = create_JavaIoByteArrayOutputStream_initWithInt_(ComJhonjuPs3netsrvServerCommandsStatFileCommand_RESULT_LENGTH);
  JavaLangThrowable *__primaryException1 = nil;
  @try {
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->aFileSize_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->bModifiedTime_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->cCreationTime_)];
    [out writeWithByteArray:ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(self->dLastAccessTime_)];
    [out writeWithInt:eIsDirectory_ ? 1 : 0];
    return [out toByteArray];
  }
  @catch (JavaLangThrowable *e) {
    __primaryException1 = e;
    @throw e;
  }
  @finally {
    if (out != nil) {
      if (__primaryException1 != nil) {
        @try {
          [out close];
        }
        @catch (JavaLangThrowable *e) {
          [__primaryException1 addSuppressedWithJavaLangThrowable:e];
        }
      }
      else {
        [out close];
      }
    }
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x1, -1, -1, 1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithLong:withLong:withLong:withLong:withBoolean:);
  methods[1].selector = @selector(init);
  methods[2].selector = @selector(toByteArray);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "aFileSize_", "J", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "bModifiedTime_", "J", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "cCreationTime_", "J", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "dLastAccessTime_", "J", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
    { "eIsDirectory_", "Z", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "JJJJZ", "LJavaIoIOException;", "LComJhonjuPs3netsrvServerCommandsStatFileCommand;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult = { "StatFileResult", "com.jhonju.ps3netsrv.server.commands", ptrTable, methods, fields, 7, 0xa, 3, 5, 2, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult;
}

@end

void ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *self, jlong fileSize, jlong modifiedTime, jlong creationTime, jlong lastAccessTime, jboolean isDirectory) {
  NSObject_init(self);
  self->aFileSize_ = fileSize;
  self->bModifiedTime_ = modifiedTime;
  self->cCreationTime_ = creationTime;
  self->dLastAccessTime_ = lastAccessTime;
  self->eIsDirectory_ = isDirectory;
}

ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *new_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(jlong fileSize, jlong modifiedTime, jlong creationTime, jlong lastAccessTime, jboolean isDirectory) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult, initWithLong_withLong_withLong_withLong_withBoolean_, fileSize, modifiedTime, creationTime, lastAccessTime, isDirectory)
}

ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_initWithLong_withLong_withLong_withLong_withBoolean_(jlong fileSize, jlong modifiedTime, jlong creationTime, jlong lastAccessTime, jboolean isDirectory) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult, initWithLong_withLong_withLong_withLong_withBoolean_, fileSize, modifiedTime, creationTime, lastAccessTime, isDirectory)
}

void ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *self) {
  NSObject_init(self);
  self->aFileSize_ = -1LL;
  self->bModifiedTime_ = 0LL;
  self->cCreationTime_ = 0LL;
  self->dLastAccessTime_ = 0LL;
  self->eIsDirectory_ = false;
}

ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *new_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init() {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult, init)
}

ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult *create_ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult_init() {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult, init)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerCommandsStatFileCommand_StatFileResult)
