//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/commands/WriteFileCommand.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsWriteFileCommand")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerCommandsWriteFileCommand
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsWriteFileCommand 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsWriteFileCommand 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerCommandsWriteFileCommand

#if !defined (ComJhonjuPs3netsrvServerCommandsWriteFileCommand_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsWriteFileCommand || defined(INCLUDE_ComJhonjuPs3netsrvServerCommandsWriteFileCommand))
#define ComJhonjuPs3netsrvServerCommandsWriteFileCommand_

#define RESTRICT_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#define INCLUDE_ComJhonjuPs3netsrvServerCommandsAbstractCommand 1
#include "com/jhonju/ps3netsrv/server/commands/AbstractCommand.h"

@class ComJhonjuPs3netsrvServerContext;

@interface ComJhonjuPs3netsrvServerCommandsWriteFileCommand : ComJhonjuPs3netsrvServerCommandsAbstractCommand

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)ctx
                                                withInt:(jint)numBytes;

- (void)executeTask;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerCommandsWriteFileCommand)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerCommandsWriteFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_(ComJhonjuPs3netsrvServerCommandsWriteFileCommand *self, ComJhonjuPs3netsrvServerContext *ctx, jint numBytes);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsWriteFileCommand *new_ComJhonjuPs3netsrvServerCommandsWriteFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerCommandsWriteFileCommand *create_ComJhonjuPs3netsrvServerCommandsWriteFileCommand_initWithComJhonjuPs3netsrvServerContext_withInt_(ComJhonjuPs3netsrvServerContext *ctx, jint numBytes);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerCommandsWriteFileCommand)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerCommandsWriteFileCommand")
