//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/CDSectorSize.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsCDSectorSize")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerEnumsCDSectorSize
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsCDSectorSize 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsCDSectorSize 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerEnumsCDSectorSize

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComJhonjuPs3netsrvServerEnumsCDSectorSize_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsCDSectorSize || defined(INCLUDE_ComJhonjuPs3netsrvServerEnumsCDSectorSize))
#define ComJhonjuPs3netsrvServerEnumsCDSectorSize_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum) {
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2352 = 0,
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2048 = 1,
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2328 = 2,
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2336 = 3,
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2340 = 4,
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2368 = 5,
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum_CD_SECTOR_2448 = 6,
};

@interface ComJhonjuPs3netsrvServerEnumsCDSectorSize : JavaLangEnum {
 @public
  jint cdSectorSize_;
}

#pragma mark Public

+ (ComJhonjuPs3netsrvServerEnumsCDSectorSize *)valueOfWithInt:(jint)cdSectorSize;

+ (ComJhonjuPs3netsrvServerEnumsCDSectorSize *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComJhonjuPs3netsrvServerEnumsCDSectorSize)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_values_[];

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2352(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2352)

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2048(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2048)

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2328(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2328)

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2336(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2336)

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2340(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2340)

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2368(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2368)

inline ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_get_CD_SECTOR_2448(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2448)

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_valueOfWithInt_(jint cdSectorSize);

FOUNDATION_EXPORT IOSObjectArray *ComJhonjuPs3netsrvServerEnumsCDSectorSize_values(void);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerEnumsCDSectorSize)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsCDSectorSize")
