//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/CDSectorSize.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/enums/CDSectorSize.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/enums/CDSectorSize must not be compiled with ARC (-fobjc-arc)"
#endif

__attribute__((unused)) static void ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(ComJhonjuPs3netsrvServerEnumsCDSectorSize *self, jint cdSectorSize, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(ComJhonjuPs3netsrvServerEnumsCDSectorSize)

ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_values_[7];

@implementation ComJhonjuPs3netsrvServerEnumsCDSectorSize

+ (ComJhonjuPs3netsrvServerEnumsCDSectorSize *)valueOfWithInt:(jint)cdSectorSize {
  return ComJhonjuPs3netsrvServerEnumsCDSectorSize_valueOfWithInt_(cdSectorSize);
}

+ (IOSObjectArray *)values {
  return ComJhonjuPs3netsrvServerEnumsCDSectorSize_values();
}

+ (ComJhonjuPs3netsrvServerEnumsCDSectorSize *)valueOfWithNSString:(NSString *)name {
  return ComJhonjuPs3netsrvServerEnumsCDSectorSize_valueOfWithNSString_(name);
}

- (ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum)toNSEnum {
  return (ComJhonjuPs3netsrvServerEnumsCDSectorSize_Enum)[self ordinal];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "[LComJhonjuPs3netsrvServerEnumsCDSectorSize;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", 0x9, 0, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(valueOfWithInt:);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "CD_SECTOR_2352", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "CD_SECTOR_2048", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "CD_SECTOR_2328", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "CD_SECTOR_2336", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "CD_SECTOR_2340", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "CD_SECTOR_2368", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 8, -1, -1 },
    { "CD_SECTOR_2448", "LComJhonjuPs3netsrvServerEnumsCDSectorSize;", .constantValue.asLong = 0, 0x4019, -1, 9, -1, -1 },
    { "cdSectorSize_", "I", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "I", "LNSString;", &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2352), &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2048), &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2328), &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2336), &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2340), &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2368), &JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2448), "Ljava/lang/Enum<Lcom/jhonju/ps3netsrv/server/enums/CDSectorSize;>;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerEnumsCDSectorSize = { "CDSectorSize", "com.jhonju.ps3netsrv.server.enums", ptrTable, methods, fields, 7, 0x4011, 3, 8, -1, -1, -1, 10, -1 };
  return &_ComJhonjuPs3netsrvServerEnumsCDSectorSize;
}

+ (void)initialize {
  if (self == [ComJhonjuPs3netsrvServerEnumsCDSectorSize class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 7 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2352) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2352, @"CD_SECTOR_2352", 0);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2048) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2048, @"CD_SECTOR_2048", 1);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2328) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2328, @"CD_SECTOR_2328", 2);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2336) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2336, @"CD_SECTOR_2336", 3);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2340) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2340, @"CD_SECTOR_2340", 4);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2368) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2368, @"CD_SECTOR_2368", 5);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsCDSectorSize, CD_SECTOR_2448) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(e, 2448, @"CD_SECTOR_2448", 6);
    J2OBJC_SET_INITIALIZED(ComJhonjuPs3netsrvServerEnumsCDSectorSize)
  }
}

@end

void ComJhonjuPs3netsrvServerEnumsCDSectorSize_initWithInt_withNSString_withInt_(ComJhonjuPs3netsrvServerEnumsCDSectorSize *self, jint cdSectorSize, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->cdSectorSize_ = cdSectorSize;
}

ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_valueOfWithInt_(jint cdSectorSize) {
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_initialize();
  {
    IOSObjectArray *a__ = ComJhonjuPs3netsrvServerEnumsCDSectorSize_values();
    ComJhonjuPs3netsrvServerEnumsCDSectorSize * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
    ComJhonjuPs3netsrvServerEnumsCDSectorSize * const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      ComJhonjuPs3netsrvServerEnumsCDSectorSize *cdSecSize = *b__++;
      if (((ComJhonjuPs3netsrvServerEnumsCDSectorSize *) nil_chk(cdSecSize))->cdSectorSize_ == cdSectorSize) {
        return cdSecSize;
      }
    }
  }
  return nil;
}

IOSObjectArray *ComJhonjuPs3netsrvServerEnumsCDSectorSize_values() {
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_initialize();
  return [IOSObjectArray arrayWithObjects:ComJhonjuPs3netsrvServerEnumsCDSectorSize_values_ count:7 type:ComJhonjuPs3netsrvServerEnumsCDSectorSize_class_()];
}

ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_valueOfWithNSString_(NSString *name) {
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_initialize();
  for (int i = 0; i < 7; i++) {
    ComJhonjuPs3netsrvServerEnumsCDSectorSize *e = ComJhonjuPs3netsrvServerEnumsCDSectorSize_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComJhonjuPs3netsrvServerEnumsCDSectorSize *ComJhonjuPs3netsrvServerEnumsCDSectorSize_fromOrdinal(NSUInteger ordinal) {
  ComJhonjuPs3netsrvServerEnumsCDSectorSize_initialize();
  if (ordinal >= 7) {
    return nil;
  }
  return ComJhonjuPs3netsrvServerEnumsCDSectorSize_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerEnumsCDSectorSize)
