//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/EListType.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/enums/EListType.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/enums/EListType must not be compiled with ARC (-fobjc-arc)"
#endif

__attribute__((unused)) static void ComJhonjuPs3netsrvServerEnumsEListType_initWithNSString_withInt_(ComJhonjuPs3netsrvServerEnumsEListType *self, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(ComJhonjuPs3netsrvServerEnumsEListType)

ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_values_[3];

@implementation ComJhonjuPs3netsrvServerEnumsEListType

+ (IOSObjectArray *)values {
  return ComJhonjuPs3netsrvServerEnumsEListType_values();
}

+ (ComJhonjuPs3netsrvServerEnumsEListType *)valueOfWithNSString:(NSString *)name {
  return ComJhonjuPs3netsrvServerEnumsEListType_valueOfWithNSString_(name);
}

- (ComJhonjuPs3netsrvServerEnumsEListType_Enum)toNSEnum {
  return (ComJhonjuPs3netsrvServerEnumsEListType_Enum)[self ordinal];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LComJhonjuPs3netsrvServerEnumsEListType;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComJhonjuPs3netsrvServerEnumsEListType;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "LIST_TYPE_NONE", "LComJhonjuPs3netsrvServerEnumsEListType;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "LIST_TYPE_ALLOWED", "LComJhonjuPs3netsrvServerEnumsEListType;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "LIST_TYPE_BLOCKED", "LComJhonjuPs3netsrvServerEnumsEListType;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComJhonjuPs3netsrvServerEnumsEListType, LIST_TYPE_NONE), &JreEnum(ComJhonjuPs3netsrvServerEnumsEListType, LIST_TYPE_ALLOWED), &JreEnum(ComJhonjuPs3netsrvServerEnumsEListType, LIST_TYPE_BLOCKED), "Ljava/lang/Enum<Lcom/jhonju/ps3netsrv/server/enums/EListType;>;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerEnumsEListType = { "EListType", "com.jhonju.ps3netsrv.server.enums", ptrTable, methods, fields, 7, 0x4011, 2, 3, -1, -1, -1, 5, -1 };
  return &_ComJhonjuPs3netsrvServerEnumsEListType;
}

+ (void)initialize {
  if (self == [ComJhonjuPs3netsrvServerEnumsEListType class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 3 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    for (jint i = 0; i < 3; i++) {
      ((void)(ComJhonjuPs3netsrvServerEnumsEListType_values_[i] = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
      ComJhonjuPs3netsrvServerEnumsEListType_initWithNSString_withInt_(e, JreEnumConstantName(ComJhonjuPs3netsrvServerEnumsEListType_class_(), i), i);
    }
    J2OBJC_SET_INITIALIZED(ComJhonjuPs3netsrvServerEnumsEListType)
  }
}

@end

void ComJhonjuPs3netsrvServerEnumsEListType_initWithNSString_withInt_(ComJhonjuPs3netsrvServerEnumsEListType *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *ComJhonjuPs3netsrvServerEnumsEListType_values() {
  ComJhonjuPs3netsrvServerEnumsEListType_initialize();
  return [IOSObjectArray arrayWithObjects:ComJhonjuPs3netsrvServerEnumsEListType_values_ count:3 type:ComJhonjuPs3netsrvServerEnumsEListType_class_()];
}

ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_valueOfWithNSString_(NSString *name) {
  ComJhonjuPs3netsrvServerEnumsEListType_initialize();
  for (int i = 0; i < 3; i++) {
    ComJhonjuPs3netsrvServerEnumsEListType *e = ComJhonjuPs3netsrvServerEnumsEListType_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_fromOrdinal(NSUInteger ordinal) {
  ComJhonjuPs3netsrvServerEnumsEListType_initialize();
  if (ordinal >= 3) {
    return nil;
  }
  return ComJhonjuPs3netsrvServerEnumsEListType_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerEnumsEListType)
