//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/EListType.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEListType")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerEnumsEListType
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEListType 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEListType 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerEnumsEListType

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComJhonjuPs3netsrvServerEnumsEListType_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEListType || defined(INCLUDE_ComJhonjuPs3netsrvServerEnumsEListType))
#define ComJhonjuPs3netsrvServerEnumsEListType_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComJhonjuPs3netsrvServerEnumsEListType_Enum) {
  ComJhonjuPs3netsrvServerEnumsEListType_Enum_LIST_TYPE_NONE = 0,
  ComJhonjuPs3netsrvServerEnumsEListType_Enum_LIST_TYPE_ALLOWED = 1,
  ComJhonjuPs3netsrvServerEnumsEListType_Enum_LIST_TYPE_BLOCKED = 2,
};

@interface ComJhonjuPs3netsrvServerEnumsEListType : JavaLangEnum

#pragma mark Public

+ (ComJhonjuPs3netsrvServerEnumsEListType *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComJhonjuPs3netsrvServerEnumsEListType_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComJhonjuPs3netsrvServerEnumsEListType)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_values_[];

inline ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_get_LIST_TYPE_NONE(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsEListType, LIST_TYPE_NONE)

inline ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_get_LIST_TYPE_ALLOWED(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsEListType, LIST_TYPE_ALLOWED)

inline ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_get_LIST_TYPE_BLOCKED(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsEListType, LIST_TYPE_BLOCKED)

FOUNDATION_EXPORT IOSObjectArray *ComJhonjuPs3netsrvServerEnumsEListType_values(void);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsEListType *ComJhonjuPs3netsrvServerEnumsEListType_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerEnumsEListType)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEListType")
