//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/ENetIsoCommand.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/enums/ENetIsoCommand.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/enums/ENetIsoCommand must not be compiled with ARC (-fobjc-arc)"
#endif

__attribute__((unused)) static void ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(ComJhonjuPs3netsrvServerEnumsENetIsoCommand *self, jint value, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(ComJhonjuPs3netsrvServerEnumsENetIsoCommand)

ComJhonjuPs3netsrvServerEnumsENetIsoCommand *ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values_[16];

@implementation ComJhonjuPs3netsrvServerEnumsENetIsoCommand

+ (ComJhonjuPs3netsrvServerEnumsENetIsoCommand *)valueOfWithInt:(jint)command {
  return ComJhonjuPs3netsrvServerEnumsENetIsoCommand_valueOfWithInt_(command);
}

+ (IOSObjectArray *)values {
  return ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values();
}

+ (ComJhonjuPs3netsrvServerEnumsENetIsoCommand *)valueOfWithNSString:(NSString *)name {
  return ComJhonjuPs3netsrvServerEnumsENetIsoCommand_valueOfWithNSString_(name);
}

- (ComJhonjuPs3netsrvServerEnumsENetIsoCommand_Enum)toNSEnum {
  return (ComJhonjuPs3netsrvServerEnumsENetIsoCommand_Enum)[self ordinal];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "[LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", 0x9, 0, 2, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(valueOfWithInt:);
  methods[1].selector = @selector(values);
  methods[2].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "NETISO_CMD_OPEN_FILE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "NETISO_CMD_READ_FILE_CRITICAL", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
    { "NETISO_CMD_READ_CD_2048_CRITICAL", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 5, -1, -1 },
    { "NETISO_CMD_READ_FILE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 6, -1, -1 },
    { "NETISO_CMD_CREATE_FILE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 7, -1, -1 },
    { "NETISO_CMD_WRITE_FILE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 8, -1, -1 },
    { "NETISO_CMD_OPEN_DIR", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 9, -1, -1 },
    { "NETISO_CMD_READ_DIR_ENTRY", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 10, -1, -1 },
    { "NETISO_CMD_DELETE_FILE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 11, -1, -1 },
    { "NETISO_CMD_MKDIR", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 12, -1, -1 },
    { "NETISO_CMD_RMDIR", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 13, -1, -1 },
    { "NETISO_CMD_READ_DIR_ENTRY_V2", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 14, -1, -1 },
    { "NETISO_CMD_STAT_FILE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 15, -1, -1 },
    { "NETISO_CMD_GET_DIR_SIZE", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 16, -1, -1 },
    { "NETISO_CMD_READ_DIR", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 17, -1, -1 },
    { "NETISO_CMD_CUSTOM_0", "LComJhonjuPs3netsrvServerEnumsENetIsoCommand;", .constantValue.asLong = 0, 0x4019, -1, 18, -1, -1 },
    { "value_", "I", .constantValue.asLong = 0, 0x11, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "I", "LNSString;", &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_OPEN_FILE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_FILE_CRITICAL), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_CD_2048_CRITICAL), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_FILE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_CREATE_FILE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_WRITE_FILE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_OPEN_DIR), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_DIR_ENTRY), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_DELETE_FILE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_MKDIR), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_RMDIR), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_DIR_ENTRY_V2), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_STAT_FILE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_GET_DIR_SIZE), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_DIR), &JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_CUSTOM_0), "Ljava/lang/Enum<Lcom/jhonju/ps3netsrv/server/enums/ENetIsoCommand;>;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerEnumsENetIsoCommand = { "ENetIsoCommand", "com.jhonju.ps3netsrv.server.enums", ptrTable, methods, fields, 7, 0x4011, 3, 17, -1, -1, -1, 19, -1 };
  return &_ComJhonjuPs3netsrvServerEnumsENetIsoCommand;
}

+ (void)initialize {
  if (self == [ComJhonjuPs3netsrvServerEnumsENetIsoCommand class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 16 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_OPEN_FILE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1224, @"NETISO_CMD_OPEN_FILE", 0);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_FILE_CRITICAL) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1225, @"NETISO_CMD_READ_FILE_CRITICAL", 1);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_CD_2048_CRITICAL) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1226, @"NETISO_CMD_READ_CD_2048_CRITICAL", 2);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_FILE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1227, @"NETISO_CMD_READ_FILE", 3);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_CREATE_FILE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1228, @"NETISO_CMD_CREATE_FILE", 4);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_WRITE_FILE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1229, @"NETISO_CMD_WRITE_FILE", 5);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_OPEN_DIR) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x122A, @"NETISO_CMD_OPEN_DIR", 6);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_DIR_ENTRY) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x122B, @"NETISO_CMD_READ_DIR_ENTRY", 7);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_DELETE_FILE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x122C, @"NETISO_CMD_DELETE_FILE", 8);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_MKDIR) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x122D, @"NETISO_CMD_MKDIR", 9);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_RMDIR) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x122E, @"NETISO_CMD_RMDIR", 10);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_DIR_ENTRY_V2) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x122F, @"NETISO_CMD_READ_DIR_ENTRY_V2", 11);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_STAT_FILE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1230, @"NETISO_CMD_STAT_FILE", 12);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_GET_DIR_SIZE) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1231, @"NETISO_CMD_GET_DIR_SIZE", 13);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_READ_DIR) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x1232, @"NETISO_CMD_READ_DIR", 14);
    ((void) (JreEnum(ComJhonjuPs3netsrvServerEnumsENetIsoCommand, NETISO_CMD_CUSTOM_0) = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(e, (jint) 0x2412, @"NETISO_CMD_CUSTOM_0", 15);
    J2OBJC_SET_INITIALIZED(ComJhonjuPs3netsrvServerEnumsENetIsoCommand)
  }
}

@end

void ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initWithInt_withNSString_withInt_(ComJhonjuPs3netsrvServerEnumsENetIsoCommand *self, jint value, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
  self->value_ = value;
}

ComJhonjuPs3netsrvServerEnumsENetIsoCommand *ComJhonjuPs3netsrvServerEnumsENetIsoCommand_valueOfWithInt_(jint command) {
  ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initialize();
  {
    IOSObjectArray *a__ = ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values();
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand * const *b__ = ((IOSObjectArray *) nil_chk(a__))->buffer_;
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand * const *e__ = b__ + a__->size_;
    while (b__ < e__) {
      ComJhonjuPs3netsrvServerEnumsENetIsoCommand *comm = *b__++;
      if (((ComJhonjuPs3netsrvServerEnumsENetIsoCommand *) nil_chk(comm))->value_ == command) {
        return comm;
      }
    }
  }
  return nil;
}

IOSObjectArray *ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values() {
  ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initialize();
  return [IOSObjectArray arrayWithObjects:ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values_ count:16 type:ComJhonjuPs3netsrvServerEnumsENetIsoCommand_class_()];
}

ComJhonjuPs3netsrvServerEnumsENetIsoCommand *ComJhonjuPs3netsrvServerEnumsENetIsoCommand_valueOfWithNSString_(NSString *name) {
  ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initialize();
  for (int i = 0; i < 16; i++) {
    ComJhonjuPs3netsrvServerEnumsENetIsoCommand *e = ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComJhonjuPs3netsrvServerEnumsENetIsoCommand *ComJhonjuPs3netsrvServerEnumsENetIsoCommand_fromOrdinal(NSUInteger ordinal) {
  ComJhonjuPs3netsrvServerEnumsENetIsoCommand_initialize();
  if (ordinal >= 16) {
    return nil;
  }
  return ComJhonjuPs3netsrvServerEnumsENetIsoCommand_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerEnumsENetIsoCommand)
