//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/EVirtualISO.java
//

#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/enums/EVirtualISO.h"
#include "java/lang/Enum.h"
#include "java/lang/IllegalArgumentException.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/enums/EVirtualISO must not be compiled with ARC (-fobjc-arc)"
#endif

__attribute__((unused)) static void ComJhonjuPs3netsrvServerEnumsEVirtualISO_initWithNSString_withInt_(ComJhonjuPs3netsrvServerEnumsEVirtualISO *self, NSString *__name, jint __ordinal);

J2OBJC_INITIALIZED_DEFN(ComJhonjuPs3netsrvServerEnumsEVirtualISO)

ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_values_[3];

@implementation ComJhonjuPs3netsrvServerEnumsEVirtualISO

+ (IOSObjectArray *)values {
  return ComJhonjuPs3netsrvServerEnumsEVirtualISO_values();
}

+ (ComJhonjuPs3netsrvServerEnumsEVirtualISO *)valueOfWithNSString:(NSString *)name {
  return ComJhonjuPs3netsrvServerEnumsEVirtualISO_valueOfWithNSString_(name);
}

- (ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum)toNSEnum {
  return (ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum)[self ordinal];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "[LComJhonjuPs3netsrvServerEnumsEVirtualISO;", 0x9, -1, -1, -1, -1, -1, -1 },
    { NULL, "LComJhonjuPs3netsrvServerEnumsEVirtualISO;", 0x9, 0, 1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(values);
  methods[1].selector = @selector(valueOfWithNSString:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "VISO_NONE", "LComJhonjuPs3netsrvServerEnumsEVirtualISO;", .constantValue.asLong = 0, 0x4019, -1, 2, -1, -1 },
    { "VISO_PS3", "LComJhonjuPs3netsrvServerEnumsEVirtualISO;", .constantValue.asLong = 0, 0x4019, -1, 3, -1, -1 },
    { "VISO_ISO", "LComJhonjuPs3netsrvServerEnumsEVirtualISO;", .constantValue.asLong = 0, 0x4019, -1, 4, -1, -1 },
  };
  static const void *ptrTable[] = { "valueOf", "LNSString;", &JreEnum(ComJhonjuPs3netsrvServerEnumsEVirtualISO, VISO_NONE), &JreEnum(ComJhonjuPs3netsrvServerEnumsEVirtualISO, VISO_PS3), &JreEnum(ComJhonjuPs3netsrvServerEnumsEVirtualISO, VISO_ISO), "Ljava/lang/Enum<Lcom/jhonju/ps3netsrv/server/enums/EVirtualISO;>;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerEnumsEVirtualISO = { "EVirtualISO", "com.jhonju.ps3netsrv.server.enums", ptrTable, methods, fields, 7, 0x4011, 2, 3, -1, -1, -1, 5, -1 };
  return &_ComJhonjuPs3netsrvServerEnumsEVirtualISO;
}

+ (void)initialize {
  if (self == [ComJhonjuPs3netsrvServerEnumsEVirtualISO class]) {
    size_t objSize = class_getInstanceSize(self);
    size_t allocSize = 3 * objSize;
    uintptr_t ptr = (uintptr_t)calloc(allocSize, 1);
    id e;
    for (jint i = 0; i < 3; i++) {
      ((void)(ComJhonjuPs3netsrvServerEnumsEVirtualISO_values_[i] = e = objc_constructInstance(self, (void *)ptr)), ptr += objSize);
      ComJhonjuPs3netsrvServerEnumsEVirtualISO_initWithNSString_withInt_(e, JreEnumConstantName(ComJhonjuPs3netsrvServerEnumsEVirtualISO_class_(), i), i);
    }
    J2OBJC_SET_INITIALIZED(ComJhonjuPs3netsrvServerEnumsEVirtualISO)
  }
}

@end

void ComJhonjuPs3netsrvServerEnumsEVirtualISO_initWithNSString_withInt_(ComJhonjuPs3netsrvServerEnumsEVirtualISO *self, NSString *__name, jint __ordinal) {
  JavaLangEnum_initWithNSString_withInt_(self, __name, __ordinal);
}

IOSObjectArray *ComJhonjuPs3netsrvServerEnumsEVirtualISO_values() {
  ComJhonjuPs3netsrvServerEnumsEVirtualISO_initialize();
  return [IOSObjectArray arrayWithObjects:ComJhonjuPs3netsrvServerEnumsEVirtualISO_values_ count:3 type:ComJhonjuPs3netsrvServerEnumsEVirtualISO_class_()];
}

ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_valueOfWithNSString_(NSString *name) {
  ComJhonjuPs3netsrvServerEnumsEVirtualISO_initialize();
  for (int i = 0; i < 3; i++) {
    ComJhonjuPs3netsrvServerEnumsEVirtualISO *e = ComJhonjuPs3netsrvServerEnumsEVirtualISO_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw create_JavaLangIllegalArgumentException_initWithNSString_(name);
  return nil;
}

ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_fromOrdinal(NSUInteger ordinal) {
  ComJhonjuPs3netsrvServerEnumsEVirtualISO_initialize();
  if (ordinal >= 3) {
    return nil;
  }
  return ComJhonjuPs3netsrvServerEnumsEVirtualISO_values_[ordinal];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerEnumsEVirtualISO)
