//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/enums/EVirtualISO.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEVirtualISO")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerEnumsEVirtualISO
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEVirtualISO 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEVirtualISO 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerEnumsEVirtualISO

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComJhonjuPs3netsrvServerEnumsEVirtualISO_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEVirtualISO || defined(INCLUDE_ComJhonjuPs3netsrvServerEnumsEVirtualISO))
#define ComJhonjuPs3netsrvServerEnumsEVirtualISO_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum) {
  ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum_VISO_NONE = 0,
  ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum_VISO_PS3 = 1,
  ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum_VISO_ISO = 2,
};

@interface ComJhonjuPs3netsrvServerEnumsEVirtualISO : JavaLangEnum

#pragma mark Public

+ (ComJhonjuPs3netsrvServerEnumsEVirtualISO *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComJhonjuPs3netsrvServerEnumsEVirtualISO_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(ComJhonjuPs3netsrvServerEnumsEVirtualISO)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_values_[];

inline ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_get_VISO_NONE(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsEVirtualISO, VISO_NONE)

inline ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_get_VISO_PS3(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsEVirtualISO, VISO_PS3)

inline ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_get_VISO_ISO(void);
J2OBJC_ENUM_CONSTANT(ComJhonjuPs3netsrvServerEnumsEVirtualISO, VISO_ISO)

FOUNDATION_EXPORT IOSObjectArray *ComJhonjuPs3netsrvServerEnumsEVirtualISO_values(void);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerEnumsEVirtualISO *ComJhonjuPs3netsrvServerEnumsEVirtualISO_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerEnumsEVirtualISO)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerEnumsEVirtualISO")
