//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/Context.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerContext")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerContext
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerContext 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerContext 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerContext

#if !defined (ComJhonjuPs3netsrvServerContext_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerContext || defined(INCLUDE_ComJhonjuPs3netsrvServerContext))
#define ComJhonjuPs3netsrvServerContext_

#define RESTRICT_JavaLangAutoCloseable 1
#define INCLUDE_JavaLangAutoCloseable 1
#include "java/lang/AutoCloseable.h"

@class ComJhonjuPs3netsrvServerEnumsCDSectorSize;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaIoOutputStream;
@class JavaIoRandomAccessFile;
@class JavaNetInetAddress;
@class JavaNetSocket;

@interface ComJhonjuPs3netsrvServerContext : NSObject < JavaLangAutoCloseable >

#pragma mark Public

- (instancetype)initWithJavaNetSocket:(JavaNetSocket *)socket
                         withNSString:(NSString *)rootDirectory
                          withBoolean:(jboolean)readOnly;

- (void)close;

- (ComJhonjuPs3netsrvServerEnumsCDSectorSize *)getCdSectorSize;

- (JavaIoFile *)getFile;

- (JavaIoInputStream *)getInputStream;

- (JavaIoOutputStream *)getOutputStream;

- (JavaIoRandomAccessFile *)getReadOnlyFile;

- (JavaNetInetAddress *)getRemoteAddress;

- (NSString *)getRootDirectory;

- (JavaIoFile *)getWriteOnlyFile;

- (jboolean)isReadOnly;

- (jboolean)isSocketConnected;

- (void)setCdSectorSizeWithComJhonjuPs3netsrvServerEnumsCDSectorSize:(ComJhonjuPs3netsrvServerEnumsCDSectorSize *)cdSectorSize;

- (void)setFileWithJavaIoFile:(JavaIoFile *)file;

- (void)setWriteOnlyFileWithJavaIoFile:(JavaIoFile *)writeOnlyFile;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerContext)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerContext_initWithJavaNetSocket_withNSString_withBoolean_(ComJhonjuPs3netsrvServerContext *self, JavaNetSocket *socket, NSString *rootDirectory, jboolean readOnly);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerContext *new_ComJhonjuPs3netsrvServerContext_initWithJavaNetSocket_withNSString_withBoolean_(JavaNetSocket *socket, NSString *rootDirectory, jboolean readOnly) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerContext *create_ComJhonjuPs3netsrvServerContext_initWithJavaNetSocket_withNSString_withBoolean_(JavaNetSocket *socket, NSString *rootDirectory, jboolean readOnly);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerContext)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerContext")
