//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/ContextHandler.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerContextHandler")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerContextHandler
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerContextHandler 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerContextHandler 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerContextHandler

#if !defined (ComJhonjuPs3netsrvServerContextHandler_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerContextHandler || defined(INCLUDE_ComJhonjuPs3netsrvServerContextHandler))
#define ComJhonjuPs3netsrvServerContextHandler_

#define RESTRICT_JavaLangThread 1
#define INCLUDE_JavaLangThread 1
#include "java/lang/Thread.h"

@class ComJhonjuPs3netsrvServerContext;
@class JavaLangThreadGroup;
@protocol JavaLangRunnable;
@protocol JavaLangThread_UncaughtExceptionHandler;

@interface ComJhonjuPs3netsrvServerContextHandler : JavaLangThread

#pragma mark Public

- (instancetype)initWithComJhonjuPs3netsrvServerContext:(ComJhonjuPs3netsrvServerContext *)context
                                                withInt:(jint)maxConnections
            withJavaLangThread_UncaughtExceptionHandler:(id<JavaLangThread_UncaughtExceptionHandler>)exceptionHandler;

- (void)decrementSimultaneousConnections;

- (void)incrementSimultaneousConnections;

- (void)run;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangRunnable:(id<JavaLangRunnable>)arg0 NS_UNAVAILABLE;

- (instancetype)initWithJavaLangRunnable:(id<JavaLangRunnable>)arg0
                            withNSString:(NSString *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)arg0
                       withJavaLangRunnable:(id<JavaLangRunnable>)arg1 NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)arg0
                       withJavaLangRunnable:(id<JavaLangRunnable>)arg1
                               withNSString:(NSString *)arg2 NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)arg0
                       withJavaLangRunnable:(id<JavaLangRunnable>)arg1
                               withNSString:(NSString *)arg2
                                   withLong:(jlong)arg3 NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThreadGroup:(JavaLangThreadGroup *)arg0
                               withNSString:(NSString *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerContextHandler)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerContextHandler_initWithComJhonjuPs3netsrvServerContext_withInt_withJavaLangThread_UncaughtExceptionHandler_(ComJhonjuPs3netsrvServerContextHandler *self, ComJhonjuPs3netsrvServerContext *context, jint maxConnections, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerContextHandler *new_ComJhonjuPs3netsrvServerContextHandler_initWithComJhonjuPs3netsrvServerContext_withInt_withJavaLangThread_UncaughtExceptionHandler_(ComJhonjuPs3netsrvServerContext *context, jint maxConnections, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerContextHandler *create_ComJhonjuPs3netsrvServerContextHandler_initWithComJhonjuPs3netsrvServerContext_withInt_withJavaLangThread_UncaughtExceptionHandler_(ComJhonjuPs3netsrvServerContext *context, jint maxConnections, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerContextHandler)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerContextHandler")
