//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/PS3NetSrvTask.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerPS3NetSrvTask")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerPS3NetSrvTask
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerPS3NetSrvTask 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerPS3NetSrvTask 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerPS3NetSrvTask

#if !defined (ComJhonjuPs3netsrvServerPS3NetSrvTask_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerPS3NetSrvTask || defined(INCLUDE_ComJhonjuPs3netsrvServerPS3NetSrvTask))
#define ComJhonjuPs3netsrvServerPS3NetSrvTask_

#define RESTRICT_JavaLangRunnable 1
#define INCLUDE_JavaLangRunnable 1
#include "java/lang/Runnable.h"

@class ComJhonjuPs3netsrvServerEnumsEListType;
@protocol JavaLangThread_UncaughtExceptionHandler;
@protocol JavaUtilSet;

@interface ComJhonjuPs3netsrvServerPS3NetSrvTask : NSObject < JavaLangRunnable >

#pragma mark Public

- (instancetype)initWithInt:(jint)port
               withNSString:(NSString *)folderPath
                    withInt:(jint)maxConnections
                withBoolean:(jboolean)readOnly
            withJavaUtilSet:(id<JavaUtilSet>)filterAddresses
withComJhonjuPs3netsrvServerEnumsEListType:(ComJhonjuPs3netsrvServerEnumsEListType *)listType
withJavaLangThread_UncaughtExceptionHandler:(id<JavaLangThread_UncaughtExceptionHandler>)exceptionHandler;

- (instancetype)initWithInt:(jint)port
               withNSString:(NSString *)folderPath
withJavaLangThread_UncaughtExceptionHandler:(id<JavaLangThread_UncaughtExceptionHandler>)exceptionHandler;

- (void)run;

- (void)shutdown;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerPS3NetSrvTask)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerPS3NetSrvTask_initWithInt_withNSString_withInt_withBoolean_withJavaUtilSet_withComJhonjuPs3netsrvServerEnumsEListType_withJavaLangThread_UncaughtExceptionHandler_(ComJhonjuPs3netsrvServerPS3NetSrvTask *self, jint port, NSString *folderPath, jint maxConnections, jboolean readOnly, id<JavaUtilSet> filterAddresses, ComJhonjuPs3netsrvServerEnumsEListType *listType, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerPS3NetSrvTask *new_ComJhonjuPs3netsrvServerPS3NetSrvTask_initWithInt_withNSString_withInt_withBoolean_withJavaUtilSet_withComJhonjuPs3netsrvServerEnumsEListType_withJavaLangThread_UncaughtExceptionHandler_(jint port, NSString *folderPath, jint maxConnections, jboolean readOnly, id<JavaUtilSet> filterAddresses, ComJhonjuPs3netsrvServerEnumsEListType *listType, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerPS3NetSrvTask *create_ComJhonjuPs3netsrvServerPS3NetSrvTask_initWithInt_withNSString_withInt_withBoolean_withJavaUtilSet_withComJhonjuPs3netsrvServerEnumsEListType_withJavaLangThread_UncaughtExceptionHandler_(jint port, NSString *folderPath, jint maxConnections, jboolean readOnly, id<JavaUtilSet> filterAddresses, ComJhonjuPs3netsrvServerEnumsEListType *listType, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler);

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerPS3NetSrvTask_initWithInt_withNSString_withJavaLangThread_UncaughtExceptionHandler_(ComJhonjuPs3netsrvServerPS3NetSrvTask *self, jint port, NSString *folderPath, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerPS3NetSrvTask *new_ComJhonjuPs3netsrvServerPS3NetSrvTask_initWithInt_withNSString_withJavaLangThread_UncaughtExceptionHandler_(jint port, NSString *folderPath, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerPS3NetSrvTask *create_ComJhonjuPs3netsrvServerPS3NetSrvTask_initWithInt_withNSString_withJavaLangThread_UncaughtExceptionHandler_(jint port, NSString *folderPath, id<JavaLangThread_UncaughtExceptionHandler> exceptionHandler);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerPS3NetSrvTask)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerPS3NetSrvTask")
