//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException

#if !defined (ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException || defined(INCLUDE_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException))
#define ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_

#define RESTRICT_JavaLangException 1
#define INCLUDE_JavaLangException 1
#include "java/lang/Exception.h"

@class JavaLangThrowable;

@interface ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException : JavaLangException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException *self, NSString *message);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException *new_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException *create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException")
