//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException.java
//

#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException.h"
#include "java/lang/Exception.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/exceptions/PS3NetSrvException must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException

- (instancetype)initWithNSString:(NSString *)message {
  ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(self, message);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LNSString;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException = { "PS3NetSrvException", "com.jhonju.ps3netsrv.server.exceptions", ptrTable, methods, NULL, 7, 0x1, 1, 0, -1, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException;
}

@end

void ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException *self, NSString *message) {
  JavaLangException_initWithNSString_(self, message);
}

ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException *new_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(NSString *message) {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException, initWithNSString_, message)
}

ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException *create_ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException_initWithNSString_(NSString *message) {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException, initWithNSString_, message)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerExceptionsPS3NetSrvException)
