name: Convert Java Android code to iOS using J2ObjC

on:
  push:
    branches: [ ObjC ]
  pull_request:
    branches: [ ObjC ]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download J2ObjC
      run: |
        curl -L -O https://github.com/google/j2objc/releases/download/2.8/j2objc-2.8.zip
        unzip j2objc-2.8.zip
        rm j2objc-2.8.zip

    - name: Convert code to Objective-C
      run: |
        $PWD/j2objc-2.8/j2objc -sourcepath $PWD/app/src/main/java --no-package-directories `find src/main/java -name '*.java'` -d $PWD/app/src/main/objc
        
    - name: Commit converted code
      run: |
        git config --global user.email "jhonathan.correa@outlook.com"
        git config --global user.name "Jhonathan Corrêa"
        git add -A
        git commit -m "Converted Java code to Objective-C using J2ObjC"
    
    - name: Push changes to remote repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ObjC
