//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/utils/Utils.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "com/jhonju/ps3netsrv/server/utils/Utils.h"
#include "java/io/File.h"
#include "java/io/InputStream.h"
#include "java/nio/ByteBuffer.h"
#include "java/nio/ByteOrder.h"
#include "java/nio/CharBuffer.h"
#include "java/nio/charset/Charset.h"
#include "java/nio/charset/StandardCharsets.h"
#include "java/util/Arrays.h"

#if __has_feature(objc_arc)
#error "com/jhonju/ps3netsrv/server/utils/Utils must not be compiled with ARC (-fobjc-arc)"
#endif

@implementation ComJhonjuPs3netsrvServerUtilsUtils

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ComJhonjuPs3netsrvServerUtilsUtils_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (IOSByteArray *)charArrayToByteArrayWithCharArray:(IOSCharArray *)chars {
  return ComJhonjuPs3netsrvServerUtilsUtils_charArrayToByteArrayWithCharArray_(chars);
}

+ (IOSByteArray *)longToBytesBEWithLong:(jlong)value {
  return ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(value);
}

+ (IOSByteArray *)intToBytesBEWithInt:(jint)value {
  return ComJhonjuPs3netsrvServerUtilsUtils_intToBytesBEWithInt_(value);
}

+ (IOSByteArray *)shortToBytesBEWithShort:(jshort)value {
  return ComJhonjuPs3netsrvServerUtilsUtils_shortToBytesBEWithShort_(value);
}

+ (jboolean)isByteArrayEmptyWithByteArray:(IOSByteArray *)byteArray {
  return ComJhonjuPs3netsrvServerUtilsUtils_isByteArrayEmptyWithByteArray_(byteArray);
}

+ (JavaNioByteBuffer *)readCommandDataWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                                    withInt:(jint)size {
  return ComJhonjuPs3netsrvServerUtilsUtils_readCommandDataWithJavaIoInputStream_withInt_(inArg, size);
}

+ (IOSLongArray *)getFileStatsWithJavaIoFile:(JavaIoFile *)file {
  return ComJhonjuPs3netsrvServerUtilsUtils_getFileStatsWithJavaIoFile_(file);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 2, 3, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 4, 5, -1, -1, -1, -1 },
    { NULL, "[B", 0x9, 6, 7, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 8, 9, -1, -1, -1, -1 },
    { NULL, "LJavaNioByteBuffer;", 0x9, 10, 11, 12, -1, -1, -1 },
    { NULL, "[J", 0x9, 13, 14, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(charArrayToByteArrayWithCharArray:);
  methods[2].selector = @selector(longToBytesBEWithLong:);
  methods[3].selector = @selector(intToBytesBEWithInt:);
  methods[4].selector = @selector(shortToBytesBEWithShort:);
  methods[5].selector = @selector(isByteArrayEmptyWithByteArray:);
  methods[6].selector = @selector(readCommandDataWithJavaIoInputStream:withInt:);
  methods[7].selector = @selector(getFileStatsWithJavaIoFile:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "SHORT_CAPACITY", "I", .constantValue.asInt = ComJhonjuPs3netsrvServerUtilsUtils_SHORT_CAPACITY, 0x19, -1, -1, -1, -1 },
    { "INT_CAPACITY", "I", .constantValue.asInt = ComJhonjuPs3netsrvServerUtilsUtils_INT_CAPACITY, 0x19, -1, -1, -1, -1 },
    { "LONG_CAPACITY", "I", .constantValue.asInt = ComJhonjuPs3netsrvServerUtilsUtils_LONG_CAPACITY, 0x19, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "charArrayToByteArray", "[C", "longToBytesBE", "J", "intToBytesBE", "I", "shortToBytesBE", "S", "isByteArrayEmpty", "[B", "readCommandData", "LJavaIoInputStream;I", "LJavaIoIOException;", "getFileStats", "LJavaIoFile;" };
  static const J2ObjcClassInfo _ComJhonjuPs3netsrvServerUtilsUtils = { "Utils", "com.jhonju.ps3netsrv.server.utils", ptrTable, methods, fields, 7, 0x1, 8, 3, -1, -1, -1, -1, -1 };
  return &_ComJhonjuPs3netsrvServerUtilsUtils;
}

@end

void ComJhonjuPs3netsrvServerUtilsUtils_init(ComJhonjuPs3netsrvServerUtilsUtils *self) {
  NSObject_init(self);
}

ComJhonjuPs3netsrvServerUtilsUtils *new_ComJhonjuPs3netsrvServerUtilsUtils_init() {
  J2OBJC_NEW_IMPL(ComJhonjuPs3netsrvServerUtilsUtils, init)
}

ComJhonjuPs3netsrvServerUtilsUtils *create_ComJhonjuPs3netsrvServerUtilsUtils_init() {
  J2OBJC_CREATE_IMPL(ComJhonjuPs3netsrvServerUtilsUtils, init)
}

IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_charArrayToByteArrayWithCharArray_(IOSCharArray *chars) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  JavaNioCharBuffer *charBuffer = JavaNioCharBuffer_wrapWithCharArray_(chars);
  JavaNioByteBuffer *byteBuffer = JreRetainedLocalValue([((JavaNioCharsetCharset *) nil_chk(JreLoadStatic(JavaNioCharsetStandardCharsets, UTF_8))) encodeWithJavaNioCharBuffer:charBuffer]);
  IOSByteArray *bytes = [IOSByteArray arrayWithLength:[((JavaNioByteBuffer *) nil_chk(byteBuffer)) remaining]];
  [byteBuffer getWithByteArray:bytes];
  JavaUtilArrays_fillWithByteArray_withByte_([byteBuffer array], (jbyte) 0);
  return bytes;
}

IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(jlong value) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  JavaNioByteBuffer *bb = JreRetainedLocalValue([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_allocateWithInt_(ComJhonjuPs3netsrvServerUtilsUtils_LONG_CAPACITY))) orderWithJavaNioByteOrder:JreLoadStatic(JavaNioByteOrder, BIG_ENDIAN)]);
  [((JavaNioByteBuffer *) nil_chk(bb)) putLongWithLong:value];
  return [bb array];
}

IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_intToBytesBEWithInt_(jint value) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  JavaNioByteBuffer *bb = JreRetainedLocalValue([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_allocateWithInt_(ComJhonjuPs3netsrvServerUtilsUtils_INT_CAPACITY))) orderWithJavaNioByteOrder:JreLoadStatic(JavaNioByteOrder, BIG_ENDIAN)]);
  [((JavaNioByteBuffer *) nil_chk(bb)) putIntWithInt:value];
  return [bb array];
}

IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_shortToBytesBEWithShort_(jshort value) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  JavaNioByteBuffer *bb = JreRetainedLocalValue([((JavaNioByteBuffer *) nil_chk(JavaNioByteBuffer_allocateWithInt_(ComJhonjuPs3netsrvServerUtilsUtils_SHORT_CAPACITY))) orderWithJavaNioByteOrder:JreLoadStatic(JavaNioByteOrder, BIG_ENDIAN)]);
  [((JavaNioByteBuffer *) nil_chk(bb)) putShortWithShort:value];
  return [bb array];
}

jboolean ComJhonjuPs3netsrvServerUtilsUtils_isByteArrayEmptyWithByteArray_(IOSByteArray *byteArray) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  return (((IOSByteArray *) nil_chk(byteArray))->size_ == 0 || JavaUtilArrays_equalsWithByteArray_withByteArray_(byteArray, [IOSByteArray arrayWithLength:byteArray->size_]));
}

JavaNioByteBuffer *ComJhonjuPs3netsrvServerUtilsUtils_readCommandDataWithJavaIoInputStream_withInt_(JavaIoInputStream *inArg, jint size) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  IOSByteArray *data = [IOSByteArray arrayWithLength:size];
  if ([((JavaIoInputStream *) nil_chk(inArg)) readWithByteArray:data] < 0) return nil;
  return JavaNioByteBuffer_wrapWithByteArray_(data);
}

IOSLongArray *ComJhonjuPs3netsrvServerUtilsUtils_getFileStatsWithJavaIoFile_(JavaIoFile *file) {
  ComJhonjuPs3netsrvServerUtilsUtils_initialize();
  return [IOSLongArray arrayWithLongs:(jlong[]){ 0, 0 } count:2];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComJhonjuPs3netsrvServerUtilsUtils)
