//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ./app/src/main/java/com/jhonju/ps3netsrv/server/utils/Utils.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerUtilsUtils")
#ifdef RESTRICT_ComJhonjuPs3netsrvServerUtilsUtils
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerUtilsUtils 0
#else
#define INCLUDE_ALL_ComJhonjuPs3netsrvServerUtilsUtils 1
#endif
#undef RESTRICT_ComJhonjuPs3netsrvServerUtilsUtils

#if !defined (ComJhonjuPs3netsrvServerUtilsUtils_) && (INCLUDE_ALL_ComJhonjuPs3netsrvServerUtilsUtils || defined(INCLUDE_ComJhonjuPs3netsrvServerUtilsUtils))
#define ComJhonjuPs3netsrvServerUtilsUtils_

@class IOSByteArray;
@class IOSCharArray;
@class IOSLongArray;
@class JavaIoFile;
@class JavaIoInputStream;
@class JavaNioByteBuffer;

@interface ComJhonjuPs3netsrvServerUtilsUtils : NSObject

#pragma mark Public

- (instancetype)init;

+ (IOSByteArray *)charArrayToByteArrayWithCharArray:(IOSCharArray *)chars;

+ (IOSLongArray *)getFileStatsWithJavaIoFile:(JavaIoFile *)file;

+ (IOSByteArray *)intToBytesBEWithInt:(jint)value;

+ (jboolean)isByteArrayEmptyWithByteArray:(IOSByteArray *)byteArray;

+ (IOSByteArray *)longToBytesBEWithLong:(jlong)value;

+ (JavaNioByteBuffer *)readCommandDataWithJavaIoInputStream:(JavaIoInputStream *)inArg
                                                    withInt:(jint)size;

+ (IOSByteArray *)shortToBytesBEWithShort:(jshort)value;

@end

J2OBJC_EMPTY_STATIC_INIT(ComJhonjuPs3netsrvServerUtilsUtils)

inline jint ComJhonjuPs3netsrvServerUtilsUtils_get_SHORT_CAPACITY(void);
#define ComJhonjuPs3netsrvServerUtilsUtils_SHORT_CAPACITY 2
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerUtilsUtils, SHORT_CAPACITY, jint)

inline jint ComJhonjuPs3netsrvServerUtilsUtils_get_INT_CAPACITY(void);
#define ComJhonjuPs3netsrvServerUtilsUtils_INT_CAPACITY 4
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerUtilsUtils, INT_CAPACITY, jint)

inline jint ComJhonjuPs3netsrvServerUtilsUtils_get_LONG_CAPACITY(void);
#define ComJhonjuPs3netsrvServerUtilsUtils_LONG_CAPACITY 8
J2OBJC_STATIC_FIELD_CONSTANT(ComJhonjuPs3netsrvServerUtilsUtils, LONG_CAPACITY, jint)

FOUNDATION_EXPORT void ComJhonjuPs3netsrvServerUtilsUtils_init(ComJhonjuPs3netsrvServerUtilsUtils *self);

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerUtilsUtils *new_ComJhonjuPs3netsrvServerUtilsUtils_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComJhonjuPs3netsrvServerUtilsUtils *create_ComJhonjuPs3netsrvServerUtilsUtils_init(void);

FOUNDATION_EXPORT IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_charArrayToByteArrayWithCharArray_(IOSCharArray *chars);

FOUNDATION_EXPORT IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_longToBytesBEWithLong_(jlong value);

FOUNDATION_EXPORT IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_intToBytesBEWithInt_(jint value);

FOUNDATION_EXPORT IOSByteArray *ComJhonjuPs3netsrvServerUtilsUtils_shortToBytesBEWithShort_(jshort value);

FOUNDATION_EXPORT jboolean ComJhonjuPs3netsrvServerUtilsUtils_isByteArrayEmptyWithByteArray_(IOSByteArray *byteArray);

FOUNDATION_EXPORT JavaNioByteBuffer *ComJhonjuPs3netsrvServerUtilsUtils_readCommandDataWithJavaIoInputStream_withInt_(JavaIoInputStream *inArg, jint size);

FOUNDATION_EXPORT IOSLongArray *ComJhonjuPs3netsrvServerUtilsUtils_getFileStatsWithJavaIoFile_(JavaIoFile *file);

J2OBJC_TYPE_LITERAL_HEADER(ComJhonjuPs3netsrvServerUtilsUtils)

#endif

#pragma pop_macro("INCLUDE_ALL_ComJhonjuPs3netsrvServerUtilsUtils")
